
# Site settings
title: Artificial Intelligence and Statistics Conference
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "/aistats2013" # the subpath of your site, e.g. /blog/
url: "http://www.aistats.org" # the base hostname & protocol for your site
#twitter_username: aistat
github_username:  aistats

author:
  name: AISTATS
comments: false
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings

ghub:
  edit: true
  repository: aistats2013
banner:
  image: resort.png


conference:
  draft: false # set to True if the programme is draft only.
  logo: logo.jpg
  hide_tentative: true
  proceedings:
    url: http://proceedings.mlr.press/v31/
    show: true
  room: Room
  venue: DoubleTree Paradise Valley Resort
  venue_url: https://doubletree3.hilton.com/en/hotels/arizona/doubletree-resort-by-hilton-hotel-paradise-valley-scottsdale-PHXSJDT/index.html
  location: Scottsdale, AZ, USA
  full_name: Artificial Intelligence and Statistics
  name: AISTATS
  year: 2013
  instance: 16th
  styling: International Conference on
  dates:
  - 2013-04-29
  - 2013-05-01

# change encoding for the generated output files to utf-8
encoding: utf-8

